name:                dessert
version:             0.0.0
github:              "jali-clarke/dessert"
license:             BSD3
author:              "Jinnah Ali-Clarke"
maintainer:          "jinnah.ali-clarke@outlook.com"
copyright:           "2019 Jinnah Ali-Clarke"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jali-clarke/dessert#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring == 0.10.8.2

library:
  source-dirs: src

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test/helpers
    - test/unit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - dessert
    - hspec == 2.7.1

  acceptance:
    main:                Spec.hs
    source-dirs:
    - test/acceptance
    - test/helpers
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - dessert
    - hspec == 2.7.1